[program:smpc]
command=/opt/smpc/venv/bin/gunicorn -c /opt/smpc/gunicorn_config.py app:app
directory=/opt/smpc
user=smpc
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/opt/smpc/logs/supervisor.log
stopwaitsecs=60
killasgroup=true
stopasgroup=true
