"""
config/__init__.py - 配置包入口

保留与原 config.py 的向后兼容，所有常量直接从此模块导出。
内部实现已按领域拆分为独立子模块。
"""

from config.app import (
    BASE_DIR, DATA_DIR, SCREENSHOT_DIR, CUMULATIVE_BASE_DIR, INDICES_BASE_DIR,
    BASE_INDEX_DIR,
)
from config.crawler import (
    CRAWL, USER_AGENT, VIEWPORT_WIDTH, VIEWPORT_HEIGHT,
    GOTO_TIMEOUT, SELECTOR_TIMEOUT, PAGE_WAIT_TIME, VIEWPORT_WAIT_TIME,
    TAB_SWITCH_WAIT_TIME, SAVE_SCREENSHOT,
    MAX_RETRIES, RETRY_DELAY, RETRY_BACKOFF, OCR_MAX_RETRIES,
    CROP_MARGIN, CROP_X_OFFSET, CROP_Y_OFFSET, CROP_HEIGHT_RATIO,
    CUMULATIVE_SECTION_SELECTOR, CUMULATIVE_TABLE_SELECTOR,
    CUMULATIVE_BODY_SELECTOR, CUMULATIVE_ROW_SELECTOR,
    COL_IDX_DATE, COL_IDX_UNIT_NAV, COL_IDX_DIV_REINVEST_NO,
    COL_IDX_SPACER, COL_IDX_DIV_REINVEST_YES, COL_IDX_CHANGE,
    BENCHMARK_SELECTOR, BENCHMARK_TEXT_PATTERN,
    CUMULATIVE_CRAWL_INTERVAL, BATCH_WAIT_BETWEEN,
)
from config.fund import (
    FUND_TYPES, ALL_TAG_KEYS, SCHEDULED_TAGS, SCHEDULED_CUMULATIVE_TAGS,
    COL, MIN_COLUMNS, CODE_PATTERN,
    get_fund_type_map, get_fund_type_lists, init_tag_model_map,
)
from config.ocr import (
    TESSERACT_PATH, OCR_PSM_MODES, NET_VALUE_DECIMAL,
)
from config.site import (
    SIMU_URL, RAW_COOKIE, get_raw_cookie, ENCRYPTION_SECRET,
)